###
POST http://localhost:5000/api/v1/admins/create
Content-Type: application/json

{
    "fullname": "Trần Thế Nhân",
    "admin_id": "2210383",
    "username": "admin123",
    "password": "admin123"
}

###

POST http://localhost:5000/api/v1/admins/login
Content-Type: application/json

{
    "username": "admin123",
    "password": "admin123"
}

###
POST https://academic-management-backend.onrender.com/api/v1/admins/login
Content-Type: application/json

{
    "username": "admin123",
    "password": "admin123"
}