
POST  http://localhost:5000/api/v1/courses/create
Content-Type: application/json

{
    "course_name" : "Nhập môn lập trình",
    "credits" : 3,
    "course_type" : "Cơ sở",
    "major" : ["Khoa học máy tính", "Kỹ thuật máy tính"],
    "faculty" : "Khoa Khoa học và Kỹ thuật Máy tính",
    "course_condition" : [],
    "student_condition" : 1
}

###
POST  https://academic-management-backend.onrender.com/api/v1/courses/get
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6IjIyMTAzODMiLCJyb2xlIjoiUXXhuqNuIHRy4buLIHZpw6puIiwiYWN0aXZlIjoxLCJpYXQiOjE3MTM2MDYxMDQsImV4cCI6MTcxMzYwOTcwNH0.dZvPeVOoKWiLSgVYigFC1Nty_a_KZUfZkP5wsklJzj8

{
   
}

###
GET http://localhost:5000/api/v1/courses/get_classes?course_id=CN2690
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoiMjQxMTA4MzAiLCJyb2xlIjoiU2luaCB2acOqbiIsImFjdGl2ZSI6MSwiaWF0IjoxNzE0NDg0NTc1LCJleHAiOjE3MTQ0ODgxNzV9.aNwBExsgOvHTPFQ3k6B8RY6Q8QJ2rIYMuo1b4QbGMFk

{
   
}