POST  http://localhost:5000/api/v1/courses/create
Content-Type: application/json

{
    "course_name" : "Hệ điều hành",
    "credit" : 3,
    "max_size" : 80,
    "course_type" : "Chuyên ngành",
    "major" : ["Khoa học máy tính", "Kỹ thuật máy tính"],
    "faculty" : "Khoa Khoa học và Kỹ thuật Máy tính",
    "course_condition" : [],
    "student_condition" : 2
}