###
POST http://localhost:5000/api/v1/classes/create
Content-Type: application/json

{
    "course_id": "CS1716",
    "program": "CLC",
    "semester": "HK241",
    "day": "Thứ 4",
    "max_students": 120,
    "period": [5, 6],
    "room": "H6-314",
    "weeks": [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
}

###
POST http://localhost:5000/api/v1/classes/register
Content-Type: application/json

{
    "course_id": "CS1716",
    "class_id": "CS1716_CC02"
}

###
POST http://localhost:5000/api/v1/classes/register
Content-Type: application/json

{
    "course_id": "CN2690",
    "class_id": "CN2690_CC01"
}

###
POST http://localhost:5000/api/v1/classes/update_score?class_id=CS1716_CQ01
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVyX2lkIjoiR1Y1MzU4NyIsInJvbGUiOiJHaeG6o25nIHZpw6puIiwiYWN0aXZlIjoxLCJpYXQiOjE3MTM5MzkzMTgsImV4cCI6MTcxMzk0MjkxOH0.dP1MgwYUbujaJCURX1Hjqk8-su_0QeGzfm_Q8kwoDz8

{
    "student_id": "24110830",
    "midterm": 10,
    "final": 10,
    "lab": 10,
    "exercise": 4
}

###
PUT http://localhost:5000/api/v1/classes/cancel_register
Content-Type: application/json

{
    "course_id": "CS1716",
    "class_id": "CS1716_CQ01"
}

###
DELETE  http://localhost:5000/api/v1/classes/delete_file?class_id=CN2690_CC01&filename=0S Labs Inclass Guide - HK221.pdf
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoiMjQyNDMwMDQiLCJyb2xlIjoiU2luaCB2acOqbiIsImFjdGl2ZSI6MSwiaWF0IjoxNzE0NzQ0NTk3LCJleHAiOjE3MTQ3ODA1OTd9.cdrDZgdk4RWBF4GUUKE_EILZHI-8-9_aHWVVJq92-Zk

{
    
}

###
GET http://localhost:5000/api/v1/classes/show_files?class_id=CS1716_CQ01
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoiMjQyNzA5NTgiLCJyb2xlIjoiU2luaCB2acOqbiIsImFjdGl2ZSI6MSwiaWF0IjoxNzEzOTQwNDU0LCJleHAiOjE3MTM5NDQwNTR9.uDU3hMyssQyMcwKe29d48b1wK3UoP0BW9xGiGPuW5ac

{
    
}

###
GET http://localhost:5000/api/v1/classes/get_files?class_id=CS1716_CQ01
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoiMjQyNzA5NTgiLCJyb2xlIjoiU2luaCB2acOqbiIsImFjdGl2ZSI6MSwiaWF0IjoxNzEzODc3NTE0LCJleHAiOjE3MTM4ODExMTR9.NyFnsBr_zdEU-cwUN6ip180QsNyjvjBpMOYN2LQseM0

{
    
}

###

GET http://localhost:5000/api/v1/classes/get?class_id=CS1716_CQ01
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoiMjQyNDMwMDQiLCJyb2xlIjoiU2luaCB2acOqbiIsImFjdGl2ZSI6MSwiaWF0IjoxNzE0ODk3NTc2LCJleHAiOjE3MTQ5MzM1NzZ9.F_nYyBbJaaXMGP0b0KdMY1BrV8GNeHlmYqcHNQaUN0c

{
    
}