###
POST  http://localhost:5000/api/v1/students/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6IjIyMTAzODMiLCJyb2xlIjoiUXXhuqNuIHRy4buLIHZpw6puIiwiYWN0aXZlIjoxLCJpYXQiOjE3MTQ2NDAyMzQsImV4cCI6MTcxNDY3NjIzNH0.QDkzXluFrrajaRRhm9GzNt06tVWAQZflgww_KSWaQTo

{
    "fullname": "Nguyễn Hoàng Long",                  
    "date_of_birth": "2004-02-12",                                     
    "gender": "Nam",                               
    "credential_id": "089204009777",               
    "phone_number": "0787919942",                  
    "contact_email": "nhan.tranthek22cs@hcmut.edu.vn",     
    "address": "Tỉnh An Giang",                                            
    "class": "MT22KH01",                           
    "faculty": "Khoa học và Kỹ thuật máy tính",    
    "major": "Khoa học máy tính",                  
    "level": "Đại học",                            
    "program": "CLC"                                                               
}

###
POST http://localhost:5000/api/v1/students/get
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6IjIyMTAzODMiLCJyb2xlIjoiUXXhuqNuIHRy4buLIHZpw6puIiwiYWN0aXZlIjoxLCJpYXQiOjE3MTQ5MzI3OTksImV4cCI6MTcxNDk2ODc5OX0.lVp-o_idUMgmHA7xl2u1sdA97k2MymazGQci_ewj3qg

{
    "student_id": "24110830"                                                                           
}

###
POST http://localhost:5000/api/v1/students/login
Content-Type: application/json

{
    "username": "long.nguyen24243004",
    "password": "Student@24243004"
}

### update student
PUT http://localhost:5000/api/v1/students/update?student_id=24270958
Content-Type: application/json

{
    "contact_email": "nhan.trantheasaan@gmail.com"                                                                           
}

### update student
DELETE http://localhost:5000/api/v1/students/delete?student_id=2212389
Content-Type: application/json

{
                                                                             
}

### update student
PUT http://localhost:5000/api/v1/students/update_password
Content-Type: application/json

{
    "username": "long.nguyen24243004",
    "password": "089204009777",
    "new_password": "Student@24243004"
}

###

GET http://localhost:5000/api/v1/students/get_classes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoiMjQyNDMwMDQiLCJyb2xlIjoiU2luaCB2acOqbiIsImFjdGl2ZSI6MSwiaWF0IjoxNzE0ODk4MDU1LCJleHAiOjE3MTQ5MzQwNTV9.fsSRnXCSaLUsRi-YL75g5-xkJwoIB7nRKm9AOIgjH6M

{
    
}

###

GET http://localhost:5000/api/v1/students/get_score
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoiMjQyNzA5NTgiLCJyb2xlIjoiU2luaCB2acOqbiIsImFjdGl2ZSI6MSwiaWF0IjoxNzEzOTQwNDU0LCJleHAiOjE3MTM5NDQwNTR9.uDU3hMyssQyMcwKe29d48b1wK3UoP0BW9xGiGPuW5ac

{
    
}