###
POST  http://localhost:5000/api/v1/students/create
Content-Type: application/json

{
    "fullname": "Nguyễn Hoàng Long",                  
    "date_of_birth": "12-02-2004",                                     
    "gender": "Nam",                               
    "credential_id": "089204009777",               
    "phone_number": "0787919942",                  
    "contact_email": "nhan.tranthek22cs@hcmut.edu.vn",     
    "address": "Tỉnh An Giang",                                            
    "class": "MT22KH01",                           
    "faculty": "Khoa học và Kỹ thuật máy tính",    
    "major": "Khoa học máy tính",                  
    "level": "Đại học",                            
    "program": "CLC"                                                               
}

###
POST http://localhost:5000/api/v1/students/get
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6IjIyMTAzODMiLCJyb2xlIjoiUXXhuqNuIHRy4buLIHZpw6puIiwiYWN0aXZlIjoxLCJpYXQiOjE3MTM2MDM4MTcsImV4cCI6MTcxMzYwNzQxN30.CAKGD633K_gP6ec-GWucvucSwhD5cNeuVE_tS_jpL2w

{
                                                                           
}
###
POST https://academic-management-backend.onrender.com/api/v1/students/login
Content-Type: application/json

{
    "username": "hoang.tran24110830",
    "password": "Nhan@tran24134447"
}

###
POST http://localhost:5000/api/v1/students/login
Content-Type: application/json

{
    "username": "long.nguyen24270958",
    "password": "Nhan@tran24134447"
}

### update student
PUT http://localhost:5000/api/v1/students/update?student_id=24270958
Content-Type: application/json

{
    "contact_email": "nhan.trantheasaan@gmail.com"                                                                           
}

### update student
DELETE http://localhost:5000/api/v1/students/delete?student_id=2212389
Content-Type: application/json

{
                                                                             
}

### update student
PUT http://localhost:5000/api/v1/students/update_password
Content-Type: application/json

{
    "username": "long.nguyen24270958",
    "password": "089204009777",
    "new_password": "Nhan@tran24134447"
}

###

GET http://localhost:5000/api/v1/students/get_classes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoiMjQyNzA5NTgiLCJyb2xlIjoiU2luaCB2acOqbiIsImFjdGl2ZSI6MSwiaWF0IjoxNzEzNjAyNTE5LCJleHAiOjE3MTM2MDYxMTl9.NjCgaKmEGR26lDlb9gmxIvaEglyv5-g_kvhqwxBPGqk

{
    
}

###
GET http://localhost:5000/api/v1/students/protected-route
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoiMjQyNzA5NTgiLCJyb2xlIjoiU2luaCB2acOqbiIsImFjdGl2ZSI6MSwiaWF0IjoxNzEzMjM4NDM2LCJleHAiOjE3MTMyNDIwMzZ9.Sl9dNeS0Buolu7dya2pXXYCBOMJoyC32ZYlpXo67jkk

###

GET http://localhost:5000/api/v1/students/get_score
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoiMjQyNzA5NTgiLCJyb2xlIjoiU2luaCB2acOqbiIsImFjdGl2ZSI6MSwiaWF0IjoxNzEzNjAzMjA3LCJleHAiOjE3MTM2MDY4MDd9.dJSVpn9aP3_wG4bogzQRVRvGVDkn6Wn1LWeWw6zwZo8

{
    
}