
### huy.bui52207
POST  http://localhost:5000/api/v1/teachers/create
Content-Type: application/json

{
    "fullname": "Bùi Đức Huy",
    "gender": "Nam",
    "date_of_birth": "26-09-2005",
    "credential_id": "012111111123",
    "phone_number": "0792222223",
    "contact_email": "nhan.tranthek22cs@hcmut.edu.vn",
    "address": "TP Hồ Chí Minh",
    "homeroom_class": "MT22KH05",
    "level": "Thạc sĩ",
    "faculty": "Khoa Khoa học và Kỹ thuật Máy tính",
    "major": "Công nghệ thông tin",
    "role": "Giảng viên",
    "subject": ["CS1716", "CN2690"]
}
### 
POST https://academic-management-backend.onrender.com/api/v1/teachers/login
Content-Type: application/json

{
    "username": "huy.bui53587",
    "password": "huy.bui53587"
}

###

GET http://localhost:5000/api/v1/teachers/get
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6IjIyMTAzODMiLCJyb2xlIjoiUXXhuqNuIHRy4buLIHZpw6puIiwiaWF0IjoxNzEzNjAxNjU2LCJleHAiOjE3MTM2MDUyNTZ9.7j40_Me9UaEpKS0oyOpBD96Rk_2mppl_-z3-ZaXuGYc

{
    
}

### 
PUT http://localhost:5000/api/v1/teachers/update?teacher_id=GV53587
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6IjIyMTAzODMiLCJyb2xlIjoiUXXhuqNuIHRy4buLIHZpw6puIiwiYWN0aXZlIjoxLCJpYXQiOjE3MTM2MDM1MjEsImV4cCI6MTcxMzYwNzEyMX0.lqi7UDxRf1JMLn9eo6iCOdxSeOm1xI2ZPB8BBn08IFw

{
    "contact_email": "huy.bui52207@gmail.com",
    "address": "An Giang"
}

###

DELETE http://localhost:5000/api/v1/teachers/delete?teacher_id=GV59066
Content-Type: application/json

{
    
}

### update password
PUT http://localhost:5000/api/v1/teachers/update_password
Content-Type: application/json

{
    "username": "huy.bui52207",
    "password": "huy.bui52207",
    "new_password": "Huy@bui52207"                                                                           
}

###
GET http://localhost:5000/api/v1/teachers/get_classes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVyX2lkIjoiR1Y1MzU4NyIsInJvbGUiOiJHaeG6o25nIHZpw6puIiwiYWN0aXZlIjoxLCJpYXQiOjE3MTM2MDM0MDgsImV4cCI6MTcxMzYwNzAwOH0.XdxRw9hJobg_Pz1VBfDtW75VPrKzV5nh7znFTba6YN8

{
    
}